# Generated by Django 5.1 on 2024-08-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_alter_car_options_alter_driver_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
